import Navbar from "@/components/layout/Navbar";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Shortcut from "@/components/layout/Shortcut";
import { GlobalContextProvider } from "@/components/context/GlobalContext";
import { ThemeProvider } from "@/components/ui/theme-provider";
import Head from "next/head";

const inter = Inter({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  manifest: "/manifest.json",
  icons: { apple: "/icon.png" },
  themeColor: "#ff0000",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${inter.className}`}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <GlobalContextProvider>
            <div className="min-h-screen flex flex-col">
              <Navbar />
              <main className="w-full h-0 grow pb-12">
                <Shortcut />
                {children}
              </main>
            </div>
          </GlobalContextProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
